name: 'Telegram Message Send Action'
description: 'Send a message to a Telegram chat with optional Markdown support'
inputs:
  bot_token:
    description: 'Telegram Bot Token'
    required: true
  chat_id:
    description: 'Telegram Chat ID'
    required: true
  message:
    description: 'Message to send'
    required: true
  markdown:
    description: 'Enable Markdown parsing'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Send message to Telegram
      shell: bash
      env:
        TELEGRAM_BOT_TOKEN: ${{ inputs.bot_token }}
        TELEGRAM_CHAT_ID: ${{ inputs.chat_id }}
        MESSAGE: ${{ inputs.message }}
        MARKDOWN: ${{ inputs.markdown }}
      run: |
        if [ "$MARKDOWN" = "true" ]; then
          PARSE_MODE="-d parse_mode=MarkdownV2"
        else
          PARSE_MODE=""
        fi
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
        -d chat_id=$TELEGRAM_CHAT_ID \
        -d text="$MESSAGE" \
        $PARSE_MODE